// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "amplifyreactapp-20181217114054-hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://amplifyreactapp-20181217114054-hostingbucket.s3-website-us-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-west-2:1302c265-1c35-4069-8fd7-a55c6b80edff",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_q6P2RdXK7",
    "aws_user_pools_web_client_id": "2m1ja26af9sr0ia52k8agraj6j"
};


export default awsmobile;
